[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
centralized-connection = "CgXQcZ26YLCoqM1wUK4nCXBwtbNeVZoZgt8ueVJ8Bva1"
mock-dapp-multi = "8Q4FvsHCWK68EzYtsstdFYwUL1SHCiuLPRDJk1gaKiQ8"
xcall = "GzoCoosp8fJg7Qci1HbywnSCVr3RVcngBtB5MTUD8vuf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
