[toolchain]

[features]
resolution = false
skip-lint = false

[programs.devnet]
centralized-connection = "4vfkXyxMxptmREF3RaFKUwnPRuqsXJJeUFzpCjPSSVMb"
mock-dapp-multi = "FiVbT6SdmDt6tiARaCdxvD1q9wY8GZEiw2xbdVA5kNF7"
xcall = "EirUdPrXn6AvFJKJXq2i12Crry4KgrWCSwtRjjQy3DV9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
add-connection-mock-dapp = "yarn ts-node --project ./tsconfig.json ./scripts/mock-dapp-multi/add-connection.ts"
initialize-centralized = "yarn ts-node --project ./tsconfig.json ./scripts/centralized-connection/initialize.ts"
initialize-mock-dapp-multi = "yarn ts-node --project ./tsconfig.json ./scripts/mock-dapp-multi/initialize.ts"
initialize-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/xcall/initialize.ts"
set-admin-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/xcall/set-admin.ts"
set-protocol-fee-handler-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/xcall/set-protocol-fee-handler.ts"
set-protocol-fee-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/xcall/set-protocol-fee.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
