[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
centralized-connection = "5U3CgESS3wbVD7LsUZsLo9gYFaw9PFkazdXRtNs5bh8t"
mock-dapp-multi = "7PpmdU536NgtFwudxSGVB1H7gXbEifXxc2jrqUo89zZX"
xcall = "9Fspq2pWy4uo8UtDtuxbQUas45W1p49t2gYPpxpfZmTy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init-contract = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/begin-initialize/*.ts"
initialize-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/initialize_xcall.ts"
initialize-centralized = "yarn ts-node --project ./tsconfig.json ./scripts/initialize_centralized.ts"
initialize-mock-dapp-multi = "yarn ts-node --project ./tsconfig.json ./scripts/initialize_mock_dapp_multi.ts"
set-admin-xcall = "yarn ts-node --project ./tsconfig.json ./scripts/set_xcall_admin.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
