[addresses]
  mock_dapp = '0xf3b8de32899e4cd2036032045e95b2e0924c34c517ff9273f7eb34ab7544eb79'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.xcall]
    local = '../xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'mock_dapp'
  published-at = '0xf3b8de32899e4cd2036032045e95b2e0924c34c517ff9273f7eb34ab7544eb79'
