[addresses]
  mock_dapp = '0xb3bcf633835681a2e27049ada34ea02b95811e27c8698b208f317dbb16d6e754'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.xcall]
    local = '../xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'mock_dapp'
  published-at = '0xb3bcf633835681a2e27049ada34ea02b95811e27c8698b208f317dbb16d6e754'
