[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = ["@iconfoundation/btp2-solidity-library=../library","@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]