[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]


[rpc_endpoints]
binance_testnet = "${BINANCE_TESTNET_RPC_URL}"

remappings = ["@iconfoundation/btp2-solidity-library=../library","@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]
