[addresses]
  xcall = '0x1c53e2304b957a2dc6facccc53d2dd3c2e08066614ea05a5c0af14d72ac496e3'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.sui_rlp]
    local = '../libs/sui_rlp'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.alpha'
  name = 'xcall'
  published-at = '0x3638b141b349173a97261bbfa33ccd45334d41a80584db6f30429e18736206fe'
