name: Solidity contracts Codecov

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "contracts/evm/**"
      - ".github/workflows/solidity-cov.yml"
  push:
    branches:
      - "**"

# defaults:
#   run:
#     working-directory: contracts/evm

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    #   PROJECT_PATH: /home/runner/work
    steps:
    #   - name: Checkout
        # uses: actions/checkout@v3
        # with:
        #   submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build Contracts
        run: |
          cd /home/runner/work/
          mkdir repo
          cd repo
          git clone git@github.com:icon-project/xcall-multi.git
          git checkout feature/add-solidity-code-coverages
          forge remappings
          forge build
      - name: Generate code coverage
        run: |
          export PATH=$PATH:$HOME/.config/.foundry/bin
          forge coverage --report lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: solidity
          fail_ci_if_error: true
